package dev.mela.app.ui

import dev.mela.engine.model.GalleryMedia

data class LibraryActions(
    val sharedActivity: suspend (String, Int) -> dev.mela.engine.model.SharedActivityPage = { _, _ -> error("Unavailable") },
    val sharedPostDiscussion: suspend (String) -> dev.mela.engine.model.SharedDiscussion = { error("Unavailable") },
    val sharedPostPhotos: suspend (String) -> List<String> = { emptyList() },
    val pendingSharedInvitations: suspend () -> List<dev.mela.engine.model.SharedInvitation> = { emptyList() },
    val resolveSharedInvitation: suspend (String) -> dev.mela.engine.model.SharedInvitation = { error("Unavailable") },
    val respondSharedInvitation: suspend (String, Boolean) -> Unit = { _, _ -> error("Unavailable") },
    val sharedManagement: suspend (String) -> dev.mela.engine.model.SharedAlbumManagement = { error("Unavailable") },
    val sharedDiscussion: suspend (String) -> dev.mela.engine.model.SharedDiscussion = { error("Unavailable") },
    val changeSharedAlbum: suspend (String, dev.mela.engine.model.SharedCommand) -> Unit = { _, _ -> error("Unavailable") },
    val prefetchPreviews: (List<String>) -> Unit = {},
    val loadViewer: suspend (String) -> Unit = {},
    val selectItems: (Set<String>, Boolean) -> Unit = { _, _ -> },
    val trash: (List<GalleryMedia>, Boolean) -> Unit = { _, _ -> },
    val edit: (GalleryMedia) -> Unit = {},
    val favorites: (List<String>, Boolean) -> Unit = { _, _ -> },
    val removeFromAlbum: (String, List<String>) -> Unit = { _, _ -> },
    val cloudTrash: (List<String>, Boolean) -> Unit = { _, _ -> },
    val favorite: (String, Boolean) -> Unit = { _, _ -> },
    val contributeToSharedAlbum: (String, List<String>) -> Unit = { _, _ -> },
    val createSharedAlbum: (String, dev.mela.engine.model.SharedAlbumGeneration) -> Unit = { _, _ -> },
    val createAlbum: (String) -> Unit = {},
    val createAlbumWithPhotos: (String, List<String>) -> Unit = { _, _ -> },
    val deleteAlbum: (String) -> Unit = {},
    val cancelShare: () -> Unit = {},
    val share: (List<GalleryMedia>) -> Unit = {},
    val renameAlbum: (String, String) -> Unit = { _, _ -> },
    val addToAlbum: (String, List<String>) -> Unit = { _, _ -> },
    val saveToGallery: (GalleryMedia) -> Unit = {},
    val exportOriginal: (GalleryMedia) -> Unit = {},
    val exportLivePhoto: (GalleryMedia) -> Unit = {},
    val checkConnection: () -> Unit = {},
    val cancelDownloadBatch: (String) -> Unit = {},
    val cancelOfflineDownload: () -> Unit = {},
    val checkPhoneStorage: () -> Unit = {},
    val clearLocalMedia: (dev.mela.engine.model.LocalMediaCategory) -> Unit = {},
)
